TITLE:
run.files() iterator crashes when there are more than 50 files.

LABEL:
bug

STATE:
closed

BODY:
Hi,

It seems like the pagination is not working as intended, and if a run has more than 50 files, iterating through them crashes the code. 

Here's an illustrative example: 
```python
for file in run.files():
    print(file.name)
```

As soon as it hits file 50, I get this error:
```bash
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-73-e5e50f41f32f> in <module>
----> 1 for file in run.files():
      2     print(file.name)

~/miniconda3/envs/dimrl/lib/python3.6/site-packages/wandb/apis/public.py in __next__(self)
    222         self.index += 1
    223         if len(self.objects) <= self.index:
--> 224             if not self._load_page():
    225                 raise StopIteration
    226         return self.objects[self.index]

~/miniconda3/envs/dimrl/lib/python3.6/site-packages/wandb/apis/public.py in _load_page(self)
    207             return False
    208         self.variables.update(
--> 209             {'perPage': self.per_page, 'cursor': self.cursor})
    210         self.last_response = self.client.execute(
    211             self.QUERY, variable_values=self.variables)

~/miniconda3/envs/dimrl/lib/python3.6/site-packages/wandb/apis/public.py in cursor(self)
    527     def cursor(self):
    528         if self.last_response:
--> 529             return self.last_response['project']['run']['files']['edges'][-1]['cursor']
    530         else:
    531             return None

KeyError: 'cursor'
```

Is there a quick way I can fix this? 

