TITLE:
[Q] Sort of timeout between wandb.init and wandb.log call

LABEL:
c:misc

STATE:
closed

BODY:
Hi,

Sorry if my question is obvious but with the following code in my notebook:
```python
wandb.init(project = 'notebook_tf_MNIST',
                     config = {  
                         "learning_rate": 0.001,
                         "epochs": 10,
                         "batch_size": 64,
                         "dropout": 0.2,
                         "loss_function": "sparse_categorical_crossentropy",
                         "architecture": "CNN",
                         "dataset": "MNIST",
                         "resume" : "auto"
                     }
)

# some code

wandb.log({'Test error rate': round((1 - accuracy) * 100, 2)})
```

If I wait a couple of times (several minutes) between the call of `init` and `log` I've the following error: `Error: You must call wandb.init() before wandb.log()`

Is there a timeout between the call of `init` and the call of `log` function ?


