TITLE:
`wand on` and `wandb off` fail with TypeError

LABEL:
bug,stale

STATE:
closed

BODY:
I've set weights and biases off with `wandb off`, but coming back to it now I can't turn it back on. It seems I can't run any wandb commands from the CLI.
Setup:
Python 3.8.5
Ubuntu 20.04
wandb-0.10.7
In a conda environment with conda 4.9.0

![image](https://user-images.githubusercontent.com/30478652/97116259-69dd8300-16d2-11eb-979c-0b2ed66763e1.png)


