TITLE:
cannot set dir with wandb.init

LABEL:
bug

STATE:
closed

BODY:
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.18
* Python version: 3.6.8
* Operating System: Linux

### Description

I am trying to use a custom directory for wandb.

### What I Did

I cannot use `wandb.init(dir="my_custom_dir")`

Here is the trackeback reported:
```
wandb: WARNING Path my_custom_dir/wandb/ wasn't writable, using system temp directory
```


